### PR TITLE
Vendor libraries and Dockerfile

### PR DESCRIPTION
**Pull request by simon3z**
This WIP PR adds the vendor libraries and Dockerfile.

### CODE REVIEW

**Comment by simon3z** [comment]
cc @juliusv @ilackarms

**Comment by juliusv** [comment]
@simon3z Could you rebase this on master and include latest added dependencies (like gorilla/mux)?

**Comment by juliusv** [comment]
@simon3z Looks good as a start, let me know when you think it's ready to merge.

**Comment by simon3z** [comment]
@juliusv I wanted to think a little bit more about this over the week anyway. So up to you whether to merge this (I can do a follow-up PR if needed) or wait.

**Comment by juliusv** [comment]
@simon3z SGTM to merge it for now then!

**Pull request merged**
